sudo: false

language: cpp

compiler:
  - gcc

install: true

before_script:
  - cmake CMakeLists.txt

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./tests/tests

notifications:
  email: false