sudo: false

language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

install:
  - export CXX="g++-4.9"

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - ${CXX} --version
  - make
  - ./tests/tests

notifications:
  email: false
