sudo: false

language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - gcc-5.0
      - g++-5.0
      - libcurl4-openssl-dev
      - cmake
      - cmake-data

install:
  - export CXX="g++-5.0"

before_script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake ..

script:
  - ${CXX} --version
  - cmake --build .
  - ./tests/tests

notifications:
  email: false
